import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Carrinho',
  description: 'Generated by Luis Felipe Vieira',
}

export default function CartLayout({
  children,
}: {
  children: React.ReactNode
}) 

{
  return (
    <html lang="en">
      <body>
        {children}
        </body>
    </html>
  )
}
